  :SETUP:
#+FILE_NAME: ../Materials/Project4/example_nutrition.ipynb
#+PROPERTY: header-args:jupyter-python :tangle ../Materials/Project4/example_nutrition.py
  :END:

* Nutrient Demands
** Introduction
 In our last project we used data to estimate systems of food demand
 using different datasets.  An output from that project was as set of
 =cfe.Regression= objects; these bundle together both data and the results
 from the demand system estimation, and can be used for prediction as
 well.

 Here we'll explore some of the uses of the =cfe.Regression= class, using
 an instance created previously (as in Project 3).

After having estimated a demand system using data from our favorite country, we can imagine different counterfactual scenarios.  What if prices were different?  What if we give a cash transfer to a household?  What if school fees reduce the budget for food?  What are the consequences of any of these for diet & nutrition?

 If you don't already have the latest version of the =CFEDemands= package
 installed, grab it, along with some dependencies:
 #+begin_src jupyter-python
 #%pip install -r requirements.txt
 #+end_src

 #+begin_src jupyter-python :results silent
import pandas as pd
import cfe.regression as rgsn
 #+end_src

** From Sheet to DataFrame to Regression Object

We begin by defining a dictionary that contains the spreadsheet key.
One is provided for the Ugandan example that I wish to work
through.
#+begin_src jupyter-python :results silent 
Uganda_Data = '1yFWlP5N7Aowaj6t2roRSFFUC50aFD-RLBGfzGtqLl0w'
#+end_src

With the spreadsheet defined , grab it and define a couple of
dataframes. (Sheets should be shared with =students@eep153.iam.gserviceaccount.com=):

#+begin_src jupyter-python :results silent
import pandas as pd
import numpy as np
from eep153_tools.sheets import read_sheets

# Change 'Uganda_Data' to key of your own sheet in Sheets, above
x = read_sheets(Uganda_Data,sheet='Food Expenditures (2019-20)')
x = x.set_index(['i','t','m','j']).squeeze()


# Now prices
p = read_sheets(Uganda_Data,sheet='Food Prices (2019-20)').set_index(['t','m','j','u'])

# Compute medians of prices for particular time, place and unit
p = p.groupby(['t','m','j','u']).median()

# Just keep metric units
p = p.xs('Kg',level="u").squeeze().unstack('j')

# Get intersection of goods we have prices *and* expenditures for:
jidx = p.columns.intersection(x.index.levels[-1])

# Drop prices for goods we don't have expenditures for
p = p[jidx].T

# Household characteristics
d = read_sheets(Uganda_Data,sheet="Household Characteristics")
d.columns.name = 'k'

# Fill blanks with zeros
d = d.replace(np.nan,0)

# Expenditures x may have duplicate columns
x = x.T.groupby(['i','t','m','j']).sum()
x = x.replace(0,np.nan) # Replace zeros with missing

# Take logs of expenditures; call this y
y = np.log(x)

d.set_index(['i','t','m'],inplace=True)
#+end_src

This gives a dataframe of household characteristics $d$ with a simple structure.

#+begin_src jupyter-python :tangle no
d.head()
#+end_src

Also a dataframe of log expenditures $y$ with a similarly simple
structure.  Note that any expenditures of zero are dropped and
replaced with a missing value indicator.
#+begin_src jupyter-python :tangle no
y.head()
#+end_src

Finally, construct a regression object:
#+begin_src jupyter-python 
r = rgsn.Regression(y=y,d=d)
#+end_src

** Additional Data
Using the data on household characteristics and (log) expenditures, we can estimate the demand system (=d=,=y=).  This gives us predictions of expenditures on different kinds of foods.  Then if we divide these expenditures by prices, we get predicted quantities of food.

However, here we're interested in nutritional outcomes, so we need a food conversion table:
#+begin_src jupyter-python 
fct = read_sheets(Uganda_Data,sheet='FCT')

fct = fct.set_index('j')
fct.columns.name = 'n'

fct = fct.apply(lambda x: pd.to_numeric(x,errors='coerce'))
#+end_src

We also want to establish when nutrition is /adequate/ for households with different compositions.  For this, we want data on recommended dietary intakes:
#+begin_src jupyter-python 
rdi = read_sheets(Uganda_Data,sheet='RDI')

rdi = rdi.set_index('n')
rdi.columns.name = 'k'

rdi = rdi.apply(lambda x: pd.to_numeric(x,errors='coerce'))
#+end_src

*** Pre-estimated Demand Systems
 An instance =r= of =cfe.Regression= can be made persistent with
 =r.to_pickle('my_result.pickle')=, which saves the instance "on disk", and can be loaded using =cfe.regression.read_pickle=.  We use  this method below to load data and demand system previously estimated for Uganda:
#+begin_src jupyter-python
# Assumes you've already set this up e.g., in Project 3
r = rgsn.read_pickle('../Project3/uganda_estimates.rgsn')  
#+end_src

*** Reference Prices
Choose reference prices.  Here we'll choose a particular year, and average prices across markets.  If you wanted to focus on particular market you'd do this differently.
#+begin_src jupyter-python
# Reference prices chosen from a particular time; average across place.
# These are prices per kilogram:
pbar = p.loc[r.beta.index].mean(axis=1).fillna(1) # Only use prices for goods we can estimate
#+end_src

*** Budgets

Get food budget for all households, then find median budget:
#+begin_src jupyter-python
import numpy as np

xhat = r.predicted_expenditures()

# Total food expenditures per household
xbar = xhat.groupby(['i','t','m']).sum()

# Reference budget
xref = xbar.quantile(0.5)  # Household at 0.5 quantile is median
#+end_src

*** Food Quantities
Get quantities of food by dividing expenditures by prices:
#+begin_src jupyter-python
qhat = (xhat.unstack('j')/pbar).dropna(how='all')

# Drop missing columns
qhat = qhat.loc[:,qhat.count()>0]

qhat
#+end_src

Finally, define a function to change a single price in the vector $p$:
 #+begin_src jupyter-python :results silent
def my_prices(j,p0,p=pbar):
    """
    Change price of jth good to p0, holding other prices fixed at p.
    """
    p = p.copy()
    p.loc[j] = p0
    return p
 #+end_src

** Demands
*** Demand functions
#+begin_src jupyter-python :tangle no
%matplotlib inline
#+end_src
#+begin_src jupyter-python
import matplotlib.pyplot as plt

use = 'Matoke'  # Good we want demand curve for

# Vary prices from 50% to 200% of reference.
scale = np.linspace(.5,2,20)

# Demand for Matoke for household at median budget
plt.plot([r.demands(xref,my_prices(use,pbar[use]*s,pbar))[use] for s in scale],scale)

# Demand for Matoke for household at 25% percentile
plt.plot([r.demands(xbar.quantile(0.25),my_prices(use,pbar[use]*s,pbar))[use] for s in scale],scale)

# Demand for Matoke for household at 75% percentile
plt.plot([r.demands(xbar.quantile(0.75),my_prices(use,pbar[use]*s,pbar))[use] for s in scale],scale)

plt.ylabel(f"Price (relative to base of {pbar[use]:.2f})")
plt.xlabel(f"Quantities of {use} Demanded")

#+end_src
*** Engel Curves

#+begin_src jupyter-python
fig,ax = plt.subplots()

scale = np.geomspace(.01,10,50)

ax.plot(np.log(scale*xref),[r.expenditures(s*xref,pbar)/(s*xref) for s in scale])
ax.set_xlabel(f'log budget (relative to base of {xref:.0f})')
ax.set_ylabel(f'Expenditure share')
ax.set_title('Engel Curves')
#+end_src

** Mapping to Nutrients

 We've seen how to map prices and budgets into vectors of consumption
 quantities using =cfe.Regression.demands=.  Next we want to think about
 how to map these into bundles of /nutrients/.  The information needed
 for the mapping comes from a "Food Conversion Table" (or database,
 such as the [[https://fdc.nal.usda.gov/][USDA Food Data Central]]).    We've already grabbed an FCT, let's take a look:
 #+begin_src jupyter-python
fct
 #+end_src

 We need the index of the Food Conversion Table (FCT) to match up with
 the index of the vector of quantities demanded.   To manage this we
 make use of the =align= method for =pd.DataFrames=:
 #+begin_src jupyter-python

# Create a new FCT and vector of consumption that only share rows in common:
fct0,c0 = fct.align(qhat.T,axis=0,join='inner')
print(fct0.index)
 #+end_src

 Now, since rows of =fct0= and =c0= match, we can obtain nutritional
 outcomes from the inner (or dot, or matrix) product of the transposed
 =fct0= and =c0=:

 #+begin_src jupyter-python
# The @ operator means matrix multiply
N = fct0.T@c0

N  #NB: Uganda quantities are for previous 7 days
 #+end_src

 Of course, since we can compute the nutritional content of a vector of
 consumption goods =c0=, we can also use our demand functions to
 compute nutrition as a /function/ of prices and budget.  

 #+begin_src jupyter-python
def nutrient_demand(x,p):
    c = r.demands(x,p)
    fct0,c0 = fct.align(c,axis=0,join='inner')
    N = fct0.T@c0

    N = N.loc[~N.index.duplicated()]
    
    return N
 #+end_src

 With this =nutrient_demand= function in hand, we can see how nutrient
 outcomes vary with budget, given prices:
 #+begin_src jupyter-python
import numpy as np
import matplotlib.pyplot as plt

X = np.linspace(xref/5,xref*5,50)

UseNutrients = ['Protein','Energy','Iron','Calcium','Vitamin C']

df = pd.concat({myx:np.log(nutrient_demand(myx,pbar))[UseNutrients] for myx in X},axis=1).T
ax = df.plot()

ax.set_xlabel('log budget')
ax.set_ylabel('log nutrient')
 #+end_src


 Now how does nutrition vary with prices?

 #+begin_src jupyter-python
USE_GOOD = 'Oranges'

scale = np.geomspace(.01,10,50)

ndf = pd.DataFrame({s:np.log(nutrient_demand(xref/2,my_prices(USE_GOOD,pbar[USE_GOOD]*s)))[UseNutrients] for s in scale}).T

ax = ndf.plot()

ax.set_xlabel('log price')
ax.set_ylabel('log nutrient')
 #+end_src


** Nutritional Needs of Households
   Our data on demand and nutrients is at the /household/ level; we
   can't directly compare household level nutrition with individual
   level requirements.  What we *can* do is add up minimum individual
   requirements, and see whether household total exceed these.  This
   isn't a guarantee that all individuals have adequate nutrition
   (since the way food is allocated in the household might be quite
   unequal, or unrelated to individual requirements), but it is
   /necessary/ if all individuals are to have adequate nutrition.

   For the average household in our data, the number of
   different kinds of people can be computed by averaging over households:
#+begin_src jupyter-python :results silent
# In first round, averaged over households and villages
dbar = r.d[rdi.columns].mean()
#+end_src

Now, the inner/dot/matrix product between =dbar= and the =rdi=
DataFrame of requirements will give us minimum requirements for the
average household:
#+begin_src jupyter-python
# This matrix product gives minimum nutrient requirements for
# the average household
hh_rdi = rdi@dbar

hh_rdi
#+end_src

* Nutritional Adequacy of Food Demands
Since we can trace out demands for nutrients as a function of $(x,p)$,
and we've computed minimum nutritional requirements for the average
household, we can /normalize/ nutritional intake to check the adequacy
of diet for a household with counts of different kinds of people given by =z=.
#+begin_src jupyter-python :results silent
def nutrient_adequacy_ratio(x,p,d,rdi=rdi,days=7):
    hh_rdi = rdi.replace('',0)@d*days

    return nutrient_demand(x,p)/hh_rdi
#+end_src

In terms of normalized nutrients, any household with more than one
unit of any given nutrient (or zero in logs) will be consuming a
minimally adequate level of the nutrient; below this level there's
clearly nutritional inadequacy.  For this reason the ratio of
actual nutrients to required nutrients is termed the "nutrient
adequacy ratio," or NAR.

#+begin_src jupyter-python
X = np.geomspace(.01*xref,2*xref,100)

pd.DataFrame({x:np.log(nutrient_adequacy_ratio(x,pbar,dbar))[UseNutrients] for x in X}).T.plot()
plt.legend(UseNutrients)
plt.xlabel('budget')
plt.ylabel('log nutrient adequacy ratio')
plt.axhline(0)
plt.axvline(xref)
#+end_src

As before, we can also vary relative prices.  Here we trace out
nutritional adequacy varying the price of a single good:
#+begin_src jupyter-python
scale = np.geomspace(.01,2,50)

ndf = pd.DataFrame({s*pbar[USE_GOOD]:np.log(nutrient_adequacy_ratio(xref/4,my_prices(USE_GOOD,pbar[USE_GOOD]*s),dbar))[UseNutrients] for s in scale}).T

fig,ax = plt.subplots()
ax.plot(ndf['Vitamin C'],ndf.index)
ax.axhline(pbar[USE_GOOD])
ax.axvline(0)

ax.set_ylabel('Price')
ax.set_xlabel('log nutrient adequacy ratio')
#+end_src
